@extends('frontend.layout')

@section('content')





    <div class="container">
        <div class="about-content bd-bottom">
            <div class="row">
                <div class="col justify-content-center">
                   <h1 style="text-align: center; background-color: #00b1b1; color: #ffffff; height: 250px; width: 100%; padding-top:120px">Məxfilik Siyasəti</h1>
                    <p class="p">On www.reyoungel.com(from now on,will be referred as&nbsp;reyoungel.com),visitor privacy is of our serious concern.This privacy policy page describes what kind of personal information may be received and collected by&nbsp;reyoungel.com and how the information will be used.</p>
                    <p class="p">Search Engine Ads</p>
                    <p class="p">As many other professional sites,reyoungel.com invest on the internet advertisement.Our advertise partners include bing Ads (Google&nbsp;Ads).In order to maximize online advertising ROI and to find target clients,reyoungel.com applied some tracking codes generated by those search engines to record user IPs and page viewing flows.</p>
                    <p class="p">Business Contact Data</p>
                    <p class="p">We collect all the business contact data sent through emails or web forms on&nbsp;reyoungel.com from visitors.The visitor identification and contact related data entered will be kept strictly for&nbsp;reyoungel.com&rsquo;s internal use.reyoungel.com will ensure the safety and proper usage of those data.</p>
                    <p class="p">Information Usage</p>
                    <p class="p">We will only use your personally identifiable information as described below,unless you have specifically consented to another type of use,either at the time the personally identifiable information is collected from you or through some other form of consent from you:</p>
                    <p class="p">1.We will use personally identifiable information to complete any orders you have placed.</p>
                    <p class="p">2.We will use personally identifiable information to provide you with the specific services that you have requested,such as to reach a retailer.</p>
                    <p class="p">3.We will use your personally identifiable information to respond to questions that you send to us.</p>
                    <p class="p">4.We will use your personally identifiable information to send you emails from time to time,such as newsletters and notices about our promotions.</p>
                    <p class="p">5.We may disclose personally identifiable information as required by law or legal process.</p>
                    <p class="p">6.We may disclose personally identifiable information to investigate suspected fraud,harassment or other violations of any law,rule or regulation,or the terms or policies for the Web site.</p>
                    <p class="p">Opt Out/Corrections</p>
                    <p class="p">Upon your request,we will (a) correct or update your personal information;(b) stop sending emails to your email address; and/or (c) disable your account to prevent any future purchases through that account.You can make these requests at the customer information section,or by telephoning,or emailing your request to&nbsp;reyoungel.com&rsquo;s Customer Support department at&nbsp;bioha@info.reyoungel.com&nbsp; Please do not email your credit card number or other sensitive information.</p>

                </div>
        </div>


    </div>

@endsection
